name: generate animation

on:
  schedule:
    - cron: "0 */5 * * *" 
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step to install the necessary dependencies for the 'canvas' module
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev libpango1.0-dev libgif-dev

      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: thisisshivamgupta
          outputs: |
            dist/github-snake.svg?color_dots=#e0e0e0,#00cc00,#009900,#006600,#003300
            dist/github-snake-dark.svg?palette=github-dark&color_dots=#4d4d4d,#00cc00,#009900,#006600,#003300
            dist/ocean.gif?color_snake=orange&color_dots=#e0e0e0,#00cc00,#009900,#006600,#003300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # push the content of <build_dir> to a branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
